version: "2"
services:
  <%= name %>:
    <% if (!imageName) { %>
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          environment: "<%= environment %>"
    <% } %>
    <% if (imageName) { %>
    image: <%= imageName %>
    <% } %>
    ports:
      - "<%= servicePort %>:80"
